version: '3.8'

services:
  postgres:
    image: postgis/postgis:13-3.1
    container_name: agrotech_database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: agrotech
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: agrotech
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - agrotech_network

  redis:
    image: redis:7-alpine
    container_name: agrotech_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - agrotech_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: agrotech_pgadmin
    depends_on:
      - postgres
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - agrotech_network

volumes:
  pgdata:
  redis_data:
  pgadmin_data:

networks:
  agrotech_network:
    driver: bridge
