services:
  postgres:
    image: postgis/postgis:13-3.1
    container_name: agrotech_database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: agrotech
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: agrotech
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - agrotech_network
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: '700M'
        reservations:
          cpus: '0.20'
          memory: '300M'

  redis:
    image: redis:7-alpine
    container_name: agrotech_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --maxmemory 150mb
      --maxmemory-policy allkeys-lru
    networks:
      - agrotech_network
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: '200M'

  pgadmin:
    image: dpage/pgadmin4
    container_name: agrotech_pgadmin
    depends_on:
      - postgres
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - agrotech_network
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '300M'

volumes:
  pgdata:
  redis_data:
  pgadmin_data:

networks:
  agrotech_network:
    driver: bridge