version: '3.8'

services:
  postgres:
    image: postgis/postgis:13-3.1
    container_name: agrotech_database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: agrotech
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: agrotech
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - agrotech_network
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: '700M'
        reservations:
          cpus: '0.20'
          memory: '300M'

  redis:
    image: redis:7-alpine
    container_name: agrotech_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --appendonly yes
      --maxmemory 150mb
      --maxmemory-policy allkeys-lru
    networks:
      - agrotech_network
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: '200M'

  pgadmin:
    image: dpage/pgadmin4
    container_name: agrotech_pgadmin
    depends_on:
      - postgres
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - agrotech_network
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '300M'

  n8n:
    image: n8nio/n8n:1.80.2
    container_name: agrotech_n8n
    ports:
      - '5678:5678'
    environment:
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      NODE_ENV: production
      WEBHOOK_URL: https://transitively-unfleshly-sanora.ngrok-free.dev/
      GENERIC_TIMEZONE: America/Bogota
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - agrotech_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '500M'
        reservations:
          cpus: '0.20'
          memory: '250M'

volumes:
  pgdata:
  redis_data:
  pgadmin_data:
  n8n_data:

networks:
  agrotech_network:
    driver: bridge
